[2014-01-19 21:35:51] log.ERROR: exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '123', Array)
#1 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(128): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2472): Illuminate\Database\DatabaseManager->connection(NULL)
#6 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2438): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1527): Illuminate\Database\Eloquent\Model->getConnection()
#8 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1461): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(56): Illuminate\Database\Eloquent\Model->newQuery()
#10 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(267): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#11 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#12 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Support/Manager.php(129): call_user_func_array(Array, Array)
#13 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array)
#14 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array)
#15 /home/mentor/public_html/mentor/app/controllers/HomeController.php(59): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#16 /home/mentor/public_html/mentor/app/controllers/HomeController.php(59): Illuminate\Support\Facades\Auth::attempt(Array)
#17 [internal function]: HomeController->login()
#18 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#19 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('login', Array)
#20 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'login', Array)
#21 [internal function]: Illuminate\Routing\{closure}()
#22 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#23 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#24 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#27 /home/mentor/public_html/mentor/public/index.php(49): Illuminate\Foundation\Application->run()
#28 {main} [] []
[2014-01-19 21:36:16] log.ERROR: exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '123', Array)
#1 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(41): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(128): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#4 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#5 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2472): Illuminate\Database\DatabaseManager->connection(NULL)
#6 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2438): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#7 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1527): Illuminate\Database\Eloquent\Model->getConnection()
#8 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1461): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#9 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(56): Illuminate\Database\Eloquent\Model->newQuery()
#10 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(267): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#11 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#12 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Support/Manager.php(129): call_user_func_array(Array, Array)
#13 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array)
#14 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array)
#15 /home/mentor/public_html/mentor/app/controllers/HomeController.php(59): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#16 /home/mentor/public_html/mentor/app/controllers/HomeController.php(59): Illuminate\Support\Facades\Auth::attempt(Array)
#17 [internal function]: HomeController->login()
#18 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#19 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('login', Array)
#20 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'login', Array)
#21 [internal function]: Illuminate\Routing\{closure}()
#22 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#23 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#24 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#27 /home/mentor/public_html/mentor/public/index.php(49): Illuminate\Foundation\Application->run()
#28 {main} [] []
[2014-01-19 22:24:19] log.ERROR: exception 'ErrorException' with message 'Undefined index: mentor_id' in /home/mentor/public_html/mentor/app/controllers/UserController.php:205
Stack trace:
#0 /home/mentor/public_html/mentor/app/controllers/UserController.php(205): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/home/mentor/pu...', 205, Array)
#1 [internal function]: UserController->newAccountSave()
#2 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('newAccountSave', Array)
#4 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'newAccountSave', Array)
#5 [internal function]: Illuminate\Routing\{closure}()
#6 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#7 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#8 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/mentor/public_html/mentor/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-01-19 22:28:59] log.ERROR: exception 'ErrorException' with message 'Undefined index: mentor_id' in /home/mentor/public_html/mentor/app/controllers/UserController.php:205
Stack trace:
#0 /home/mentor/public_html/mentor/app/controllers/UserController.php(205): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/home/mentor/pu...', 205, Array)
#1 [internal function]: UserController->newAccountSave()
#2 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('newAccountSave', Array)
#4 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'newAccountSave', Array)
#5 [internal function]: Illuminate\Routing\{closure}()
#6 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#7 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#8 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/mentor/public_html/mentor/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-01-19 22:32:22] log.ERROR: exception 'ErrorException' with message 'Undefined index: mentor_id' in /home/mentor/public_html/mentor/app/controllers/UserController.php:205
Stack trace:
#0 /home/mentor/public_html/mentor/app/controllers/UserController.php(205): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/home/mentor/pu...', 205, Array)
#1 [internal function]: UserController->newAccountSave()
#2 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('newAccountSave', Array)
#4 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'newAccountSave', Array)
#5 [internal function]: Illuminate\Routing\{closure}()
#6 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array)
#7 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable()
#8 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/mentor/public_html/mentor/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/mentor/public_html/mentor/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
